### ISSUE TITLE
There is no configuration :(

### ISSUE THREAD

**Issue by seriousfreezing** [StartsMercury/visual-snowy-leaves#4]
I tested it with Modmenu, I tested it by searching for the configuration file and it doesn't take/exist a configuration file.

**Comment by StartsMercury** [comment]
> I tested it with Modmenu, I tested it by searching for the configuration file and it doesn't take/exist a configuration file.

Which version of Minecraft of the mod? Also, does pressing the `Configure...` button on this mod's mod menu entry do nothing? Pressing it should be showing the config by automatically opening youtlr text editor. (There's no config screen)

**Comment by seriousfreezing** [comment]
visual-snowy-leaves-0.4.0+mc1.21.1

Yep, does nothing. In this case, it doesn't create any configuration files

**Comment by StartsMercury** [comment]
That's not good... Could you also check the logs? Those of note are ones containing `[Visual Snowy Leaves]` and see if anything's up? Or send a whole chunk of the logs since finding those lines may be tedious. (I can't make a fix rn).

**Comment by seriousfreezing** [comment]
Also, fix the resourcepack version.
https://paste.atlauncher.com/view/da19df9b-c313-4289-a3e9-c4f90f8886a4

**Comment by seriousfreezing** [comment]
Summary:
[20/11/2024 22:50:32 PM] [Render thread/WARN] [Visual Snowy Leaves] Unable to read config json
[20/11/2024 22:50:32 PM] 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[20/11/2024 22:50:32 PM] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[20/11/2024 22:50:32 PM] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[20/11/2024 22:50:32 PM] 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:119)
[20/11/2024 22:50:32 PM] 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:309)
[20/11/2024 22:50:32 PM] 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:369)
[20/11/2024 22:50:32 PM] 	at java.base/java.nio.file.Files.lines(Files.java:4112)
[20/11/2024 22:50:32 PM] 	at java.base/java.nio.file.Files.lines(Files.java:4207)
[20/11/2024 22:50:32 PM] 	at knot//io.github.startsmercury.visual_snowy_leaves.impl.client.VisualSnowyLeavesImpl.loadConfig(VisualSnowyLeavesImpl.java:123)
[20/11/2024 22:50:32 PM] 	at knot//io.github.startsmercury.visual_snowy_leaves.impl.client.VisualSnowyLeavesImpl.reloadConfig(VisualSnowyLeavesImpl.java:109)
[20/11/2024 22:50:32 PM] 	at knot//io.github.startsmercury.visual_snowy_leaves.impl.client.entrypoint.VisualSnowyLeavesModMenu.openConfigFile(VisualSnowyLeavesModMenu.java:20)
[20/11/2024 22:50:32 PM] 	at knot//io.github.startsmercury.visual_snowy_leaves.impl.client.entrypoint.VisualSnowyLeavesModMenu$1.method_25426(VisualSnowyLeavesModMenu.java:30)
[20/11/2024 22:50:32 PM] 	at knot//net.minecraft.class_437.method_25423(class_437.java:309)
[20/11/2024 22:50:32 PM] 	at knot//net.minecraft.class_310.method_1507(class_310.java:1143)
[20/11/2024 22:50:32 PM] 	at knot//com.terraformersmc.modmenu.gui.ModsScreen.safelyOpenConfigScreen(ModsScreen.java:647)
[20/11/2024 22:50:32 PM] 	at knot//com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.openConfig(ModListEntry.java:182)
[20/11/2024 22:50:32 PM] 	at knot//com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25402(ModListEntry.java:172)
[20/11/2024 22:50:32 PM] 	at knot//com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25402(ModListWidget.java:294)
[20/11/2024 22:50:32 PM] 	at knot//net.minecraft.class_4069.method_25402(class_4069.java:38)
[20/11/2024 22:50:32 PM] 	at knot//net.minecraft.class_312.method_1611(class_312.java:107)
[20/11/2024 22:50:32 PM] 	at knot//net.minecraft.class_437.method_25412(class_437.java:431)
[20/11/2024 22:50:32 PM] 	at knot//net.minecraft.class_312.method_1601(class_312.java:107)
[20/11/2024 22:50:32 PM] 	at knot//net.minecraft.class_312.method_22686(class_312.java:196)
[20/11/2024 22:50:32 PM] 	at knot//net.minecraft.class_1255.execute(class_1255.java:108)
[20/11/2024 22:50:32 PM] 	at knot//net.minecraft.class_312.method_22684(class_312.java:196)
[20/11/2024 22:50:32 PM] 	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[20/11/2024 22:50:32 PM] 	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
[20/11/2024 22:50:32 PM] 	at knot//org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
[20/11/2024 22:50:32 PM] 	at knot//com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184)
[20/11/2024 22:50:32 PM] 	at knot//net.minecraft.class_310.method_1523(class_310.java:1310)
[20/11/2024 22:50:32 PM] 	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
[20/11/2024 22:50:32 PM] 	at knot//net.minecraft.client.main.Main.main(Main.java:256)
[20/11/2024 22:50:32 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[20/11/2024 22:50:32 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[20/11/2024 22:50:32 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by StartsMercury** [comment]
> Also, fix the resourcepack version.

I forgot! NooooOo. I will update the resourcepack version(s)... anything other than the one for 1.20.1 is not updated, great job me X)

Also thank you for the log update.

**Comment by seriousfreezing** [comment]
It's a canonical event that a mod stops updating to old versions XD
If you need more logs, just ask

**Comment by StartsMercury** [comment]
I think that's all the logs, thanks! The mod's logs are actually lacking and it is partially my fault, and probably the logger.

**Comment by StartsMercury** [comment]
I think that's all the logs we need, thanks! The mod's logs are actually lacking and it is partially my fault, and probably the logger.

**Comment by StartsMercury** [comment]
I think that's all the logs we need, thanks! The mod's logs are actually lacking and it is partially my fault, and probably the logger.

**Comment by StartsMercury** [comment]
The issue was a logic error that prevented the generation of the config file. `0.4.1` just released and it should hopefully fixes this and the resource pack version.

**Comment by seriousfreezing** [comment]
It seems that this has been fixed, but in my modpack your mod is not working correctly, I will see which mod is the problem.

And from what I've seen, the resource pack version is still wrong.

**Comment by StartsMercury** [comment]
> And from what I've seen, the resource pack version is still wrong.

Oh! I just checked, it's using data pack version numbers instead of resource pack version numbers. Great :')
